[tool.poetry]
name = "asop-bot"
version = "0.1.0"
description = ""
authors = ["JP Barela"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.24.0"
openai = "^0.27.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
